version: "3.2"

services:
  dev:
    container_name: node-validator
    image: paritytech/ci-linux:production
    working_dir: /var/www/node-validator
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/node-validator/.cargo
    volumes:
      - .:/var/www/node-validator
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/node-validator --dev --ws-external"
